obj-m += lab3_1.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=/home/kushagra/intro_to_os/kk5395_hw3 modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=/home/kushagra/intro_to_os/kk5395_hw3 clean
